package com.zhr.sqlitedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEWS.
 */
public class News {

    private Long id;
    /** Not-null value. */
    private String icon;
    /** Not-null value. */
    private String link;
    /** Not-null value. */
    private String content;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String category;

    public News() {
    }

    public News(Long id) {
        this.id = id;
    }

    public News(Long id, String icon, String link, String content, String title, String category) {
        this.id = id;
        this.icon = icon;
        this.link = link;
        this.content = content;
        this.title = title;
        this.category = category;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIcon() {
        return icon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /** Not-null value. */
    public String getLink() {
        return link;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLink(String link) {
        this.link = link;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getCategory() {
        return category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(String category) {
        this.category = category;
    }

}
